//! NIR → restricted Rust.
//!
//! The backend is a printer. Blocks become match arms, terminators become state assignments, and
//! everything about scheduling, propagation, and tracing is a call into `norn-rt` — the same calls
//! the interpreter makes, in the same order, which is what keeps the turn traces byte-identical.
//!
//! One state-numbering scheme carries the whole suspension story: block `b` of a `task fn` is
//! state `2*b`, and state `2*b + 1` re-executes only its terminator. A park leaves the frame at
//! the odd state, so waking re-asks the suspension point without re-running the instructions
//! before it — the compiled form of the interpreter's instruction pointer sitting past the end of
//! the block.

use std::collections::HashSet;

use norn_hir::hir;
use norn_nir::nir::{FnKind, Function, Instr, NodeKind, Operand, Place, Program, Rvalue, Term};

/// Which runtime access the surrounding function has. A `task fn` holds a `&mut Cx`; a plain
/// function holds an `Option` it must ask; a handler holds `None` by construction plus the turn
/// accumulator — purity as the absence of the thing every impure arm needs.
#[derive(Clone, Copy, PartialEq)]
enum Ctx {
    Task,
    Plain,
    Handler,
}

impl Ctx {
    /// The expression producing an `Option<&mut Cx>` for helpers that ask.
    fn cx_opt(self) -> &'static str {
        match self {
            Ctx::Task => "Some(&mut *cx)",
            Ctx::Plain | Ctx::Handler => "cx.as_deref_mut()",
        }
    }

    fn locals(self) -> &'static str {
        match self {
            Ctx::Task => "frame.locals",
            Ctx::Plain | Ctx::Handler => "locals",
        }
    }

    fn state(self) -> &'static str {
        match self {
            Ctx::Task => "frame.state",
            Ctx::Plain | Ctx::Handler => "block",
        }
    }

    /// The state number for a transfer to block `b`.
    fn target(self, b: usize) -> usize {
        match self {
            Ctx::Task => 2 * b,
            Ctx::Plain | Ctx::Handler => b,
        }
    }
}

pub fn generate(program: &Program, main: usize) -> String {
    let emitter = Emitter {
        program,
        handlers: program
            .reactors
            .iter()
            .flat_map(|reactor| reactor.inputs.iter().map(|input| input.handler))
            .collect(),
    };
    let mut out = String::new();
    emitter.generate(&mut out, main);
    out
}

struct Emitter<'p> {
    program: &'p Program,
    handlers: HashSet<usize>,
}

fn push(out: &mut String, indent: usize, line: &str) {
    for _ in 0..indent {
        out.push_str("    ");
    }
    out.push_str(line);
    out.push('\n');
}

fn push_all(out: &mut String, indent: usize, lines: &[String]) {
    for line in lines {
        push(out, indent, line);
    }
}

impl Emitter<'_> {
    fn generate(&self, out: &mut String, main: usize) {
        push(
            out,
            0,
            "// Generated by `norn build`. Do not edit: the source of truth is the .norn file.",
        );
        push(out, 0, "#![allow(warnings)]");
        push(out, 0, "");
        push(out, 0, "use std::io;");
        push(out, 0, "use std::process::ExitCode;");
        push(out, 0, "use std::rc::Rc;");
        push(out, 0, "");
        push(out, 0, "use norn_rt::graph::{InputSpec, ReactorSpec};");
        push(out, 0, "use norn_rt::{");
        push(
            out,
            0,
            "    Body, Clock, Config, Cx, Effect, Engine, Graph, Handled, NodeSpec, Overflow, Poll,",
        );
        push(
            out,
            0,
            "    ReactorId, ResourceId, ResourceKind, Runtime, Step, Stdout, Trap, Update,",
        );
        push(out, 0, "};");
        push(out, 0, "");
        out.push_str(crate::PRELUDE);
        push(out, 0, "");
        self.tables(out, main);
        for id in 0..self.program.fns.len() {
            self.function(out, id);
        }
        self.dispatchers(out);
        self.graph(out);
        self.specs(out);
    }

    // ------------------------------------------------------------ tables

    fn tables(&self, out: &mut String, main: usize) {
        push(
            out,
            0,
            "// ---------------------------------------------------------------- program tables",
        );
        push(out, 0, "");
        push(out, 0, "static STRUCTS: &[StructLayout] = &[");
        for strukt in &self.program.structs {
            let fields: Vec<String> = strukt.fields.iter().map(|f| format!("{f:?}")).collect();
            push(
                out,
                1,
                &format!(
                    "StructLayout {{ name: {:?}, fields: &[{}] }},",
                    strukt.name,
                    fields.join(", ")
                ),
            );
        }
        push(out, 0, "];");
        push(out, 0, "");
        push(out, 0, "static ENUMS: &[EnumLayout] = &[");
        for def in &self.program.enums {
            push(
                out,
                1,
                &format!("EnumLayout {{ name: {:?}, variants: &[", def.name),
            );
            for variant in &def.variants {
                let fields: Vec<String> = variant.fields.iter().map(|f| format!("{f:?}")).collect();
                push(
                    out,
                    2,
                    &format!(
                        "VariantLayout {{ name: {:?}, fields: &[{}], positional: {} }},",
                        variant.name,
                        fields.join(", "),
                        variant.positional
                    ),
                );
            }
            push(out, 1, "] },");
        }
        push(out, 0, "];");
        push(out, 0, "");
        let names: Vec<String> = self
            .program
            .fns
            .iter()
            .map(|f| format!("{:?}", f.name))
            .collect();
        push(
            out,
            0,
            &format!("static FN_NAMES: &[&str] = &[{}];", names.join(", ")),
        );
        let locals: Vec<String> = self
            .program
            .fns
            .iter()
            .map(|f| format!("{}usize", f.locals.len()))
            .collect();
        push(
            out,
            0,
            &format!("static FN_LOCALS: &[usize] = &[{}];", locals.join(", ")),
        );
        let tasks: Vec<String> = self
            .program
            .fns
            .iter()
            .map(|f| format!("{}", f.kind == FnKind::Task))
            .collect();
        push(
            out,
            0,
            &format!("static FN_IS_TASK: &[bool] = &[{}];", tasks.join(", ")),
        );
        push(out, 0, &format!("const MAIN_FN: usize = {main}usize;"));
        push(out, 0, "");
    }

    // ------------------------------------------------------------ functions

    fn function(&self, out: &mut String, id: usize) {
        let function = &self.program.fns[id];
        match function.kind {
            FnKind::Task => self.task_fn(out, id, function),
            FnKind::Plain if self.handlers.contains(&id) => {
                push(out, 0, &format!("// handler fn {} #{id}", function.name));
                push(
                    out,
                    0,
                    &format!(
                        "fn f{id}(turn: &mut Handled<Value>, args: Vec<Value>) -> Result<Value, Trap> {{"
                    ),
                );
                push(out, 1, "let mut cx: Option<&mut Cx<'_, '_, Value>> = None;");
                self.plain_body(out, function, Ctx::Handler);
                push(out, 0, "}");
                push(out, 0, "");
            }
            FnKind::Plain => {
                push(out, 0, &format!("// fn {} #{id}", function.name));
                push(
                    out,
                    0,
                    &format!(
                        "fn f{id}(mut cx: Option<&mut Cx<'_, '_, Value>>, args: Vec<Value>) -> Result<Value, Trap> {{"
                    ),
                );
                self.plain_body(out, function, Ctx::Plain);
                push(out, 0, "}");
                push(out, 0, "");
            }
        }
    }

    /// The shared shape of a function that cannot park: a block variable and one arm per block.
    fn plain_body(&self, out: &mut String, function: &Function, ctx: Ctx) {
        let fname = name_lit(function);
        push(
            out,
            1,
            &format!(
                "let mut locals = vec![Value::Unit; {}usize];",
                function.locals.len()
            ),
        );
        push(out, 1, "for (slot, value) in locals.iter_mut().zip(args) {");
        push(out, 2, "*slot = value;");
        push(out, 1, "}");
        push(out, 1, "let mut block = 0usize;");
        push(out, 1, "loop {");
        push(out, 2, "match block {");
        for (b, block) in function.blocks.iter().enumerate() {
            let mut body = Vec::new();
            for instr in &block.instrs {
                body.extend(self.instr_lines(function, ctx, instr));
            }
            body.extend(self.term_lines(function, ctx, b, &block.term));
            push(out, 3, &format!("{b}usize => {{"));
            push_all(out, 4, &body);
            push(out, 3, "}");
        }
        push(
            out,
            3,
            &format!("_ => return Err(Trap::new(\"unreachable block\", {fname})),"),
        );
        push(out, 2, "}");
        push(out, 1, "}");
    }

    fn task_fn(&self, out: &mut String, id: usize, function: &Function) {
        let fname = name_lit(function);
        push(out, 0, &format!("// task fn {} #{id}", function.name));
        push(
            out,
            0,
            &format!(
                "fn step_f{id}(frame: &mut Frame, cx: &mut Cx<'_, '_, Value>) -> Result<Cont, Trap> {{"
            ),
        );
        push(out, 1, "loop {");
        push(out, 2, "match frame.state {");
        for (b, block) in function.blocks.iter().enumerate() {
            let mut body = Vec::new();
            for instr in &block.instrs {
                body.extend(self.instr_lines(function, Ctx::Task, instr));
            }
            let term = self.term_lines(function, Ctx::Task, b, &block.term);
            body.extend(term.iter().cloned());
            push(out, 3, &format!("{}usize => {{", 2 * b));
            push_all(out, 4, &body);
            push(out, 3, "}");
            // The parkable terminators get a second arm that re-executes them alone.
            if matches!(block.term, Term::Await { .. } | Term::ScopeExit { .. }) {
                push(out, 3, &format!("{}usize => {{", 2 * b + 1));
                push_all(out, 4, &term);
                push(out, 3, "}");
            }
        }
        push(
            out,
            3,
            &format!("_ => return Err(Trap::new(\"unreachable state\", {fname})),"),
        );
        push(out, 2, "}");
        push(out, 1, "}");
        push(out, 0, "}");
        push(out, 0, "");
    }

    // ------------------------------------------------------------ instructions

    fn instr_lines(&self, function: &Function, ctx: Ctx, instr: &Instr) -> Vec<String> {
        let fname = name_lit(function);
        match instr {
            Instr::Assign(place, rvalue) => {
                let expr = self.rvalue_expr(function, ctx, rvalue);
                vec![format!("let value = {expr};"), write_stmt(ctx, place, "value")]
            }
            Instr::ScopeEnter => match ctx {
                Ctx::Task => vec!["cx.scope_enter();".into()],
                _ => vec![
                    "match cx.as_deref_mut() { Some(cx) => cx.scope_enter(), None => return Err(impure_trap(\"scope\")) };"
                        .into(),
                ],
            },
            Instr::Spawn(operand) => {
                let value = operand_expr(ctx, operand);
                match ctx {
                    Ctx::Task => vec![format!("spawn_task(cx, {value}, {fname})?;")],
                    _ => vec![format!(
                        "match cx.as_deref_mut() {{ Some(cx) => spawn_task(cx, {value}, {fname})?, None => return Err(impure_trap(\"spawn\")) }};"
                    )],
                }
            }
            Instr::SpawnReactor { dest, reactor, args } => {
                let args = self.args_list(ctx, args);
                let create = format!("Value::Reactor(cx.create_reactor({reactor}usize, vec![{args}])?)");
                let first = match ctx {
                    Ctx::Task => format!("let value = {create};"),
                    _ => format!(
                        "let value = match cx.as_deref_mut() {{ Some(cx) => {create}, None => return Err(impure_trap(\"spawn reactor\")) }};"
                    ),
                };
                vec![first, write_stmt(ctx, dest, "value")]
            }
            Instr::SetSlot(slot, operand) => {
                assert!(ctx == Ctx::Handler, "`set slot` outside a handler survived lowering");
                vec![format!("turn.writes.push(({slot}usize, {}));", operand_expr(ctx, operand))]
            }
            Instr::Emit { task, returns } => {
                assert!(ctx == Ctx::Handler, "`emit` outside a handler survived lowering");
                vec![format!(
                    "turn.effects.push(Effect {{ task: {}, returns: {returns:?} }});",
                    operand_expr(ctx, task)
                )]
            }
        }
    }

    // ------------------------------------------------------------ terminators

    fn term_lines(&self, function: &Function, ctx: Ctx, b: usize, term: &Term) -> Vec<String> {
        let fname = name_lit(function);
        let state = ctx.state();
        match term {
            Term::Goto(target) => vec![format!("{state} = {}usize;", ctx.target(*target))],
            Term::Branch { cond, then, els } => vec![
                format!("match {} {{", operand_expr(ctx, cond)),
                format!(
                    "    Value::Bool(true) => {state} = {}usize,",
                    ctx.target(*then)
                ),
                format!(
                    "    Value::Bool(false) => {state} = {}usize,",
                    ctx.target(*els)
                ),
                format!(
                    "    other => return Err(Trap::new(format!(\"branch on {{other:?}}\"), {fname})),"
                ),
                "}".into(),
            ],
            Term::SwitchTag {
                scrutinee,
                cases,
                default,
            } => {
                let mut lines = vec![
                    format!(
                        "let Value::Variant(_, tag, _) = {} else {{",
                        read_place_expr(ctx, scrutinee)
                    ),
                    format!(
                        "    return Err(Trap::new(\"switch on a value that is not an enum\", {fname}));"
                    ),
                    "};".into(),
                    format!("{state} = match tag {{"),
                ];
                for (tag, target) in cases {
                    lines.push(format!("    {tag}usize => {}usize,", ctx.target(*target)));
                }
                lines.push(format!("    _ => {}usize,", ctx.target(*default)));
                lines.push("};".into());
                lines
            }
            Term::Return(operand) => {
                let value = operand_expr(ctx, operand);
                match ctx {
                    Ctx::Task => vec![format!("return Ok(Cont::Return({value}));")],
                    _ => vec![format!("return Ok({value});")],
                }
            }
            Term::Trap(message) => vec![format!("return Err(Trap::new({message:?}, {fname}));")],
            Term::Await { task, dest, resume } => {
                assert!(
                    ctx == Ctx::Task,
                    "`await` outside a task fn survived lowering"
                );
                let resume = 2 * resume;
                vec![
                    format!("frame.state = {}usize;", 2 * b + 1),
                    format!("let awaited = {};", operand_expr(ctx, task)),
                    "let Value::Task(awaited) = awaited else {".into(),
                    format!("    return Err(Trap::new(\"awaited a value that is not a task\", {fname}));"),
                    "};".into(),
                    "match &awaited.kind {".into(),
                    "    TaskKind::Fn(callee, args) => {".into(),
                    format!("        frame.state = {resume}usize;"),
                    format!(
                        "        return Ok(Cont::AwaitTask {{ func: *callee, args: args.clone(), local: {}usize, proj: &{:?} }});",
                        dest.local, dest.proj
                    ),
                    "    }".into(),
                    "    TaskKind::Builtin(builtin, args) => match poll_builtin(cx, *builtin, args)? {".into(),
                    "        Poll::Ready(value) => {".into(),
                    format!("            {}", write_stmt(ctx, dest, "value")),
                    format!("            frame.state = {resume}usize;"),
                    "        }".into(),
                    "        Poll::Pending => return Ok(Cont::Park),".into(),
                    "    },".into(),
                    "}".into(),
                ]
            }
            Term::ScopeExit { resume } => {
                assert!(
                    ctx == Ctx::Task,
                    "`scope exit` outside a task fn survived lowering"
                );
                vec![
                    format!("frame.state = {}usize;", 2 * b + 1),
                    "match cx.scope_exit() {".into(),
                    format!("    Poll::Ready(()) => frame.state = {}usize,", 2 * resume),
                    "    Poll::Pending => return Ok(Cont::Park),".into(),
                    "}".into(),
                ]
            }
        }
    }

    // ------------------------------------------------------------ rvalues

    fn rvalue_expr(&self, function: &Function, ctx: Ctx, rvalue: &Rvalue) -> String {
        let fname = name_lit(function);
        match rvalue {
            Rvalue::Use(operand) => operand_expr(ctx, operand),
            Rvalue::Unary(op, operand) => {
                format!(
                    "unary(UnOp::{op:?}, {}, {fname})?",
                    operand_expr(ctx, operand)
                )
            }
            Rvalue::Binary(op, lhs, rhs) => format!(
                "binary(BinOp::{op:?}, {}, {}, {fname})?",
                operand_expr(ctx, lhs),
                operand_expr(ctx, rhs)
            ),
            Rvalue::Call(id, args) => {
                format!(
                    "f{id}({}, vec![{}])?",
                    ctx.cx_opt(),
                    self.args_list(ctx, args)
                )
            }
            Rvalue::Builtin(builtin, args) => format!(
                "eval_builtin({}, Builtin::{builtin:?}, &[{}], {fname})?",
                ctx.cx_opt(),
                self.args_list(ctx, args)
            ),
            Rvalue::Task(id, args) => format!(
                "Value::Task(Rc::new(TaskValue {{ kind: TaskKind::Fn({id}usize, vec![{}]) }}))",
                self.args_list(ctx, args)
            ),
            Rvalue::BuiltinTask(builtin, args) => format!(
                "Value::Task(Rc::new(TaskValue {{ kind: TaskKind::Builtin(Builtin::{builtin:?}, vec![{}]) }}))",
                self.args_list(ctx, args)
            ),
            Rvalue::Struct(id, args) => format!(
                "Value::Struct({id}usize, Rc::new(vec![{}]))",
                self.args_list(ctx, args)
            ),
            Rvalue::Variant(enum_id, variant, args) => format!(
                "Value::Variant({enum_id}usize, {variant}usize, Rc::new(vec![{}]))",
                self.args_list(ctx, args)
            ),
            Rvalue::ReactorInput(operand, index) => format!(
                "match {} {{ Value::Reactor(id) => Value::Input(id, {index}usize), other => return Err(Trap::new(format!(\"not a reactor handle: {{other:?}}\"), {fname})) }}",
                operand_expr(ctx, operand)
            ),
            Rvalue::ReactorExport(operand, index) => format!(
                "match {} {{ Value::Reactor(id) => Value::Signal(id, {index}usize), other => return Err(Trap::new(format!(\"not a reactor handle: {{other:?}}\"), {fname})) }}",
                operand_expr(ctx, operand)
            ),
        }
    }

    fn args_list(&self, ctx: Ctx, operands: &[Operand]) -> String {
        operands
            .iter()
            .map(|operand| operand_expr(ctx, operand))
            .collect::<Vec<_>>()
            .join(", ")
    }

    // ------------------------------------------------------------ dispatchers

    fn dispatchers(&self, out: &mut String) {
        let mut arms = Vec::new();
        for (id, function) in self.program.fns.iter().enumerate() {
            if function.kind == FnKind::Task {
                arms.push(format!("{id}usize => step_f{id}(frame, cx),"));
            }
        }
        push(
            out,
            0,
            "fn step_frame(frame: &mut Frame, cx: &mut Cx<'_, '_, Value>) -> Result<Cont, Trap> {",
        );
        push(out, 1, "match frame.func {");
        push_all(out, 2, &arms);
        push(
            out,
            2,
            "_ => Err(Trap::new(\"resumed a function that is not a task\", \"runtime\")),",
        );
        push(out, 1, "}");
        push(out, 0, "}");
        push(out, 0, "");

        let mut arms = Vec::new();
        for (id, function) in self.program.fns.iter().enumerate() {
            if function.kind == FnKind::Plain && !self.handlers.contains(&id) {
                arms.push(format!("{id}usize => f{id}(cx, args),"));
            }
        }
        push(
            out,
            0,
            "fn call_plain(func: usize, cx: Option<&mut Cx<'_, '_, Value>>, args: Vec<Value>) -> Result<Value, Trap> {",
        );
        push(out, 1, "match func {");
        push_all(out, 2, &arms);
        push(
            out,
            2,
            "_ => Err(Trap::new(\"called a function that is not plain\", \"runtime\")),",
        );
        push(out, 1, "}");
        push(out, 0, "}");
        push(out, 0, "");
    }

    // ------------------------------------------------------------ the graph engine

    fn graph(&self, out: &mut String) {
        for (id, reactor) in self.program.reactors.iter().enumerate() {
            // One pass in slot order, unrolled: parameters come before state, so everything an
            // initialiser can name has a binding by the time it is emitted.
            let mut body = Vec::new();
            let mut ready: HashSet<usize> = HashSet::new();
            let mut stuck = false;
            for &node in &reactor.slots {
                match &reactor.nodes[node].kind {
                    NodeKind::Param { index, .. } => {
                        body.push(format!(
                            "let n{node} = args.get({index}usize).cloned().ok_or_else(|| Trap::new(\"a reactor was created with too few arguments\", \"runtime\"))?;"
                        ));
                    }
                    NodeKind::State { init, .. } => {
                        if reactor.nodes[node]
                            .deps
                            .iter()
                            .any(|dep| !ready.contains(dep))
                        {
                            // The interpreter traps here at runtime; the generated program traps
                            // in the same place with the same words.
                            body.push(
                                "return Err(Trap::new(\"a state initialiser read a value that is not ready\", \"runtime\"));"
                                    .into(),
                            );
                            stuck = true;
                            break;
                        }
                        let deps: Vec<String> = reactor.nodes[node]
                            .deps
                            .iter()
                            .map(|dep| format!("n{dep}.clone()"))
                            .collect();
                        body.push(format!(
                            "let n{node} = f{init}(None, vec![{}])?;",
                            deps.join(", ")
                        ));
                    }
                    NodeKind::Signal { .. } => unreachable!("a signal holds no slot"),
                }
                ready.insert(node);
            }
            if !stuck {
                let slots: Vec<String> = reactor
                    .slots
                    .iter()
                    .map(|node| format!("n{node}.clone()"))
                    .collect();
                body.push(format!("Ok(vec![{}])", slots.join(", ")));
            }
            push(out, 0, &format!("// reactor {} #{id}", reactor.name));
            push(
                out,
                0,
                &format!("fn create_r{id}(args: Vec<Value>) -> Result<Vec<Value>, Trap> {{"),
            );
            push_all(out, 1, &body);
            push(out, 0, "}");
            push(out, 0, "");
        }

        let create_arms: Vec<String> = (0..self.program.reactors.len())
            .map(|id| format!("{id}usize => create_r{id}(args),"))
            .collect();
        let mut handle_arms = Vec::new();
        for (id, reactor) in self.program.reactors.iter().enumerate() {
            for (index, input) in reactor.inputs.iter().enumerate() {
                handle_arms.push(format!("({id}usize, {index}usize) => {{"));
                handle_arms.push(
                    "    let mut turn = Handled { writes: Vec::new(), effects: Vec::new() };"
                        .into(),
                );
                handle_arms.push("    let mut args: Vec<Value> = Vec::new();".into());
                // An input carrying `()` binds nothing, so the handler's arity says whether the
                // message is one of its arguments — resolved here rather than at runtime.
                if self.program.fns[input.handler].params == reactor.slots.len() + 1 {
                    handle_arms.push("    args.push(message);".into());
                }
                handle_arms.push("    args.extend(slots.iter().cloned());".into());
                handle_arms.push(format!("    f{}(&mut turn, args)?;", input.handler));
                handle_arms.push("    Ok(turn)".into());
                handle_arms.push("}".into());
            }
        }
        let mut recompute_arms = Vec::new();
        for (id, reactor) in self.program.reactors.iter().enumerate() {
            for (index, node) in reactor.nodes.iter().enumerate() {
                if let NodeKind::Signal { body } = node.kind {
                    // Always `Set`: the pruning v0 does is the static one, each input's plan.
                    recompute_arms.push(format!(
                        "({id}usize, {index}usize) => Ok(Update::Set(f{body}(None, deps.to_vec())?)),"
                    ));
                }
            }
        }

        push(out, 0, "struct Nodes;");
        push(out, 0, "");
        push(out, 0, "impl Graph<Value> for Nodes {");
        push(
            out,
            1,
            "fn create(&self, reactor: usize, args: Vec<Value>) -> Result<Vec<Value>, Trap> {",
        );
        push(out, 2, "match reactor {");
        push_all(out, 3, &create_arms);
        push(
            out,
            3,
            "_ => Err(Trap::new(\"created a reactor that does not exist\", \"runtime\")),",
        );
        push(out, 2, "}");
        push(out, 1, "}");
        push(out, 0, "");
        push(
            out,
            1,
            "fn handle(&self, reactor: usize, input: usize, message: Value, slots: &[Value]) -> Result<Handled<Value>, Trap> {",
        );
        push(out, 2, "match (reactor, input) {");
        push_all(out, 3, &handle_arms);
        push(
            out,
            3,
            "_ => Err(Trap::new(\"a message for an input that does not exist\", \"runtime\")),",
        );
        push(out, 2, "}");
        push(out, 1, "}");
        push(out, 0, "");
        push(
            out,
            1,
            "fn recompute(&self, reactor: usize, node: usize, deps: &[Value]) -> Result<Update<Value>, Trap> {",
        );
        push(out, 2, "match (reactor, node) {");
        push_all(out, 3, &recompute_arms);
        push(
            out,
            3,
            "_ => Err(Trap::new(\"recomputed a node that is not a signal\", \"runtime\")),",
        );
        push(out, 2, "}");
        push(out, 1, "}");
        push(out, 0, "}");
        push(out, 0, "");
    }

    // ------------------------------------------------------------ the plan as data

    fn specs(&self, out: &mut String) {
        let mut body = Vec::new();
        for reactor in &self.program.reactors {
            body.push("ReactorSpec {".to_string());
            body.push(format!("    name: {:?}.to_string(),", reactor.name));
            body.push("    nodes: vec![".into());
            for node in &reactor.nodes {
                body.push(format!(
                    "        NodeSpec {{ name: {:?}.to_string(), deps: vec![{}], slot: {:?} }},",
                    node.name,
                    list(&node.deps),
                    node.kind.slot()
                ));
            }
            body.push("    ],".into());
            body.push(format!("    slots: vec![{}],", list(&reactor.slots)));
            body.push("    inputs: vec![".into());
            for input in &reactor.inputs {
                body.push(format!(
                    "        InputSpec {{ name: {:?}.to_string(), capacity: {}usize, overflow: Overflow::{}, plan: vec![{}] }},",
                    input.name,
                    input.capacity,
                    overflow(input.overflow),
                    list(&input.plan)
                ));
            }
            body.push("    ],".into());
            body.push(format!("    order: vec![{}],", list(&reactor.order)));
            body.push(format!("    exports: vec![{}],", list(&reactor.exports)));
            body.push("},".into());
        }
        push(out, 0, "fn reactor_specs() -> Vec<ReactorSpec> {");
        push(out, 1, "vec![");
        push_all(out, 2, &body);
        push(out, 1, "]");
        push(out, 0, "}");
    }
}

/// The declared overflow policy, in the runtime's vocabulary — the same deliberate second spelling
/// as `interp::overflow`.
fn overflow(policy: hir::Overflow) -> &'static str {
    match policy {
        hir::Overflow::Reject => "Reject",
        hir::Overflow::DropOldest => "DropOldest",
        hir::Overflow::DropNewest => "DropNewest",
        hir::Overflow::Wait => "Wait",
    }
}

fn list(items: &[usize]) -> String {
    items
        .iter()
        .map(|item| format!("{item}usize"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn name_lit(function: &Function) -> String {
    format!("{:?}", function.name)
}

fn operand_expr(ctx: Ctx, operand: &Operand) -> String {
    use norn_nir::nir::Const;
    match operand {
        Operand::Const(value) => match value {
            Const::Unit => "Value::Unit".into(),
            Const::Int(v) if *v == i64::MIN => "Value::Int(i64::MIN)".into(),
            Const::Int(v) => format!("Value::Int({v}i64)"),
            // Bit-identical round-tripping: never through decimal.
            Const::Float(v) => format!(
                "Value::Float(f64::from_bits(0x{:016x}u64)) /* {v:?} */",
                v.to_bits()
            ),
            Const::Bool(v) => format!("Value::Bool({v})"),
            Const::Str(v) => format!("Value::Str(Rc::from({:?}))", &**v),
        },
        Operand::Copy(place) => read_place_expr(ctx, place),
    }
}

fn read_place_expr(ctx: Ctx, place: &Place) -> String {
    let locals = ctx.locals();
    if place.proj.is_empty() {
        format!("{locals}[{}usize].clone()", place.local)
    } else {
        format!(
            "read_place(&{locals}, {}usize, &{:?})",
            place.local, place.proj
        )
    }
}

fn write_stmt(ctx: Ctx, place: &Place, value: &str) -> String {
    let locals = ctx.locals();
    if place.proj.is_empty() {
        format!("{locals}[{}usize] = {value};", place.local)
    } else {
        format!(
            "write_place(&mut {locals}, {}usize, &{:?}, {value});",
            place.local, place.proj
        )
    }
}
