[package]
name = "norn-nir"
description = "The lowered Norn IR and its interpreter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
norn-hir.workspace = true
norn-syntax.workspace = true

[dev-dependencies]
norn-hir.workspace = true
norn-syntax.workspace = true
